{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_attributes",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5.jar",
          "url": "newnew_attributes-1.0.5.jar",
          "size": 18981,
          "sha512": "2fcab6bb37dbeb944634e8fc2d6b8a15f6087a2be61b425593fd9211511b453c5d9bb13377cfe221371c5edb680225c56cc9d5f325e4aaa423bd03c435fd8f9f",
          "sha256": "b0e50c0c6244c44af8e222442337170c690065ddecaf91e7c41b26651a0b5c09",
          "sha1": "c7118acb809c909a3c4d29d186780038ba2ce2ac",
          "md5": "8bcfb458766522175f12baaad72c8818"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_attributes-1.0.5.jar",
          "url": "newnew_attributes-1.0.5.jar",
          "size": 18981,
          "sha512": "2fcab6bb37dbeb944634e8fc2d6b8a15f6087a2be61b425593fd9211511b453c5d9bb13377cfe221371c5edb680225c56cc9d5f325e4aaa423bd03c435fd8f9f",
          "sha256": "b0e50c0c6244c44af8e222442337170c690065ddecaf91e7c41b26651a0b5c09",
          "sha1": "c7118acb809c909a3c4d29d186780038ba2ce2ac",
          "md5": "8bcfb458766522175f12baaad72c8818"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5-sources.jar",
          "url": "newnew_attributes-1.0.5-sources.jar",
          "size": 12744,
          "sha512": "d46d0059a9a00e5440fdf3f57034aa4107bf5bb50a478d7f7c7672c2d62978361e06732d2091e14aa9467affa23bfa952dcd3b5499319e1ced22cc50f9d2049a",
          "sha256": "daac31c66bce137db5f048d2970bca82eac31754d9cdb949d4b1c9bfe5f8aac3",
          "sha1": "8caf2568191c92c592dd8dffd924f24d60f9484c",
          "md5": "e61f4db69a6adf5cbc92ba1fe6d46ba6"
        }
      ]
    }
  ]
}
