{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_attributes",
    "version": "1.0.5",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5.jar",
          "url": "newnew_attributes-1.0.5.jar",
          "size": 18981,
          "sha512": "1c7c054a1beee335c14ac37614678658e51b9b26951e26f044e6721d86f484ba39704cb657e262036942fa2d666b0e6a694fe55cc4d3cd3fca22d3c5d5e2893f",
          "sha256": "11ac48e01c66aa9e77d42bb39e7da0bd69c2bc8c75361bded24e5ba84eb2b3d6",
          "sha1": "de32e4cfa340813db783528f822eaee7dd974d4b",
          "md5": "1b9ffa4c7ecf7eae074874b780ff8661"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_attributes-1.0.5.jar",
          "url": "newnew_attributes-1.0.5.jar",
          "size": 18981,
          "sha512": "1c7c054a1beee335c14ac37614678658e51b9b26951e26f044e6721d86f484ba39704cb657e262036942fa2d666b0e6a694fe55cc4d3cd3fca22d3c5d5e2893f",
          "sha256": "11ac48e01c66aa9e77d42bb39e7da0bd69c2bc8c75361bded24e5ba84eb2b3d6",
          "sha1": "de32e4cfa340813db783528f822eaee7dd974d4b",
          "md5": "1b9ffa4c7ecf7eae074874b780ff8661"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5-sources.jar",
          "url": "newnew_attributes-1.0.5-sources.jar",
          "size": 12744,
          "sha512": "d46d0059a9a00e5440fdf3f57034aa4107bf5bb50a478d7f7c7672c2d62978361e06732d2091e14aa9467affa23bfa952dcd3b5499319e1ced22cc50f9d2049a",
          "sha256": "daac31c66bce137db5f048d2970bca82eac31754d9cdb949d4b1c9bfe5f8aac3",
          "sha1": "8caf2568191c92c592dd8dffd924f24d60f9484c",
          "md5": "e61f4db69a6adf5cbc92ba1fe6d46ba6"
        }
      ]
    }
  ]
}
