{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_attributes",
    "version": "1.0.5r",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5r.jar",
          "url": "newnew_attributes-1.0.5r.jar",
          "size": 19191,
          "sha512": "de84dc9debfb80f970087f197f8423cd0824fd8419a4915c89b01618062f2f3fdab0f95c48edd88232730bf0ad874ab0c71f7fef47c3570189da890ef1f680cc",
          "sha256": "c1df771f981bc7ff08246058c5c53608f02daaeef65ae75ce905bd30ebcdcab8",
          "sha1": "641cb438324e2c301b3a3d496d2812519b0b957f",
          "md5": "ae984367f876b85ccec2c8ae1b812b72"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_attributes-1.0.5r.jar",
          "url": "newnew_attributes-1.0.5r.jar",
          "size": 19191,
          "sha512": "de84dc9debfb80f970087f197f8423cd0824fd8419a4915c89b01618062f2f3fdab0f95c48edd88232730bf0ad874ab0c71f7fef47c3570189da890ef1f680cc",
          "sha256": "c1df771f981bc7ff08246058c5c53608f02daaeef65ae75ce905bd30ebcdcab8",
          "sha1": "641cb438324e2c301b3a3d496d2812519b0b957f",
          "md5": "ae984367f876b85ccec2c8ae1b812b72"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5r-sources.jar",
          "url": "newnew_attributes-1.0.5r-sources.jar",
          "size": 12939,
          "sha512": "7d546a356ac98c2031038610fbd089657e017e60878bb2bab170a515e30928b9c9ab90bcf11356b556fd75b77ea689ac61741b0964a314c2d0c9d3da5111bc0a",
          "sha256": "be241380174c73ee67a53a553e99e91961aac8b505a6d16ad02222e2d1c60d4d",
          "sha1": "d738b78e50fee627c68a69435078ea1fe79742d8",
          "md5": "7765a2d2c23e8a182e44161e4202d7b4"
        }
      ]
    }
  ]
}
