{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_attributes",
    "version": "1.0.5r",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5r.jar",
          "url": "newnew_attributes-1.0.5r.jar",
          "size": 19195,
          "sha512": "e86c7b27567988016eb0c9332cd7a7495f1128b56b02951a33f3a58c3300535b57942abfb105507a90fe96dc3710307da34ae190ce47080ddc2c18e0c5870213",
          "sha256": "11103927a32019468a4bc1d765cdead8c65640c9b1fc530b6d266210aa845135",
          "sha1": "5baef9408b54ba29f45a23129782fc650087afe9",
          "md5": "6dc0221ec81ef0ff3be3ac355d0354b1"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_attributes-1.0.5r.jar",
          "url": "newnew_attributes-1.0.5r.jar",
          "size": 19195,
          "sha512": "e86c7b27567988016eb0c9332cd7a7495f1128b56b02951a33f3a58c3300535b57942abfb105507a90fe96dc3710307da34ae190ce47080ddc2c18e0c5870213",
          "sha256": "11103927a32019468a4bc1d765cdead8c65640c9b1fc530b6d266210aa845135",
          "sha1": "5baef9408b54ba29f45a23129782fc650087afe9",
          "md5": "6dc0221ec81ef0ff3be3ac355d0354b1"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5r-sources.jar",
          "url": "newnew_attributes-1.0.5r-sources.jar",
          "size": 12939,
          "sha512": "7d546a356ac98c2031038610fbd089657e017e60878bb2bab170a515e30928b9c9ab90bcf11356b556fd75b77ea689ac61741b0964a314c2d0c9d3da5111bc0a",
          "sha256": "be241380174c73ee67a53a553e99e91961aac8b505a6d16ad02222e2d1c60d4d",
          "sha1": "d738b78e50fee627c68a69435078ea1fe79742d8",
          "md5": "7765a2d2c23e8a182e44161e4202d7b4"
        }
      ]
    }
  ]
}
