{
  "formatVersion": "1.1",
  "component": {
    "group": "com.gam0zing",
    "module": "newnew_attributes",
    "version": "1.0.5r",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5r.jar",
          "url": "newnew_attributes-1.0.5r.jar",
          "size": 19210,
          "sha512": "a0c7a01b5c62a243278a3decd043cbeae1b28c11beb71983fab5ec9fa79db3a97ebd38a24053b13564db76ef0cd910c7820d4598e1472c19cc97d39351d55aa4",
          "sha256": "c753f239c7ce1ca7c98bb6f78c61d8360ecc28c8d09feec8fb07eb990dee9fde",
          "sha1": "a904385d6ae1a691b6f2f23a163e59b494a3ae3f",
          "md5": "97439406515fcd3ba1809eb68a61fc79"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "net.minecraftforge",
          "module": "forge",
          "version": {
            "requires": "1.20.1-47.4.1_mapped_parchment_2023.09.03-1.20.1"
          }
        }
      ],
      "files": [
        {
          "name": "newnew_attributes-1.0.5r.jar",
          "url": "newnew_attributes-1.0.5r.jar",
          "size": 19210,
          "sha512": "a0c7a01b5c62a243278a3decd043cbeae1b28c11beb71983fab5ec9fa79db3a97ebd38a24053b13564db76ef0cd910c7820d4598e1472c19cc97d39351d55aa4",
          "sha256": "c753f239c7ce1ca7c98bb6f78c61d8360ecc28c8d09feec8fb07eb990dee9fde",
          "sha1": "a904385d6ae1a691b6f2f23a163e59b494a3ae3f",
          "md5": "97439406515fcd3ba1809eb68a61fc79"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "newnew_attributes-1.0.5r-sources.jar",
          "url": "newnew_attributes-1.0.5r-sources.jar",
          "size": 12943,
          "sha512": "af68717538524dff6548b45016f5d05f26b87879acb73824e75c8cde8057d70917c5d076bc595b3db30ffb9ec7071cd2f4ec073d253f54b1d218df1981327165",
          "sha256": "df5f9c23a431055a16ebdc464555074888559bfdc556d7a5a5c7d062b86691ff",
          "sha1": "d790158c3d92d46d7629477ef71b2a73c29d94c4",
          "md5": "556c3e7e2cdc17a53a87542710b71cbe"
        }
      ]
    }
  ]
}
